//! Type generation

use crate::ir::{IR, TypeDef, TypeKind, TypeRef, FieldDef, VariantDef};
use crate::deprecation::{self, DeprecationWarning};
use crate::HUB_CODEGEN_VERSION;
use std::collections::{HashSet, HashMap};

/// Generate file header with toolchain version information.
/// Deliberately omits timestamps and IR hashes — those change on every build
/// even when file content is unchanged, causing spurious cache churn.
/// The IR hash is tracked in synapse.lock; timestamps are not useful in
/// committed generated files.
fn generate_header_comment(ir: &IR) -> Vec<String> {
    let mut header = vec![
        "/**".to_string(),
        " * Auto-generated by hub-codegen toolchain".to_string(),
        " * DO NOT EDIT MANUALLY".to_string(),
        " *".to_string(),
    ];

    if let Some(metadata) = &ir.ir_metadata {
        header.push(" * Toolchain:".to_string());
        for gen in &metadata.gm_generators {
            header.push(format!(" *   - {} v{}", gen.gi_tool, gen.gi_version));
        }
        // Add hub-codegen itself
        header.push(format!(" *   - hub-codegen v{}", HUB_CODEGEN_VERSION));
        header.push(" *".to_string());
    }

    header.push(format!(" * Backend: {}", ir.ir_backend));
    header.push(" */".to_string());
    header
}

/// Generate PlexusStreamItem and StreamMetadata - the core transport types
fn generate_core_transport_types() -> String {
    r#"// === Core Transport Types ===
// These types define the wire format for all plexus streaming responses.

/** Metadata applied by the caller when wrapping activation responses */
export interface StreamMetadata {
  /** Call path through the system (e.g., ["plexus", "health"]) */
  provenance: string[];
  /** Hash of plexus configuration for cache invalidation */
  plexusHash: string;
  /** Unix timestamp (seconds) when the event was wrapped */
  timestamp: number;
}

/** Data payload with caller-applied metadata */
export interface PlexusStreamItemData {
  type: 'data';
  /** Metadata from calling layer */
  metadata: StreamMetadata;
  /** Type identifier for deserialization (e.g., "health.status") */
  contentType: string;
  /** The actual payload (serialized activation event) */
  content: unknown;
}

/** Progress update during long-running operations */
export interface PlexusStreamItemProgress {
  type: 'progress';
  /** Metadata from calling layer */
  metadata: StreamMetadata;
  /** Human-readable progress message */
  message: string;
  /** Optional completion percentage (0.0 - 100.0) */
  percentage?: number;
}

/** Error occurred during processing */
export interface PlexusStreamItemError {
  type: 'error';
  /** Metadata from calling layer */
  metadata: StreamMetadata;
  /** Human-readable error message */
  message: string;
  /** Optional error code for programmatic handling */
  code?: string;
  /** Whether the operation can be retried */
  recoverable: boolean;
}

/** Stream completed successfully */
export interface PlexusStreamItemDone {
  type: 'done';
  /** Metadata from calling layer */
  metadata: StreamMetadata;
}

/** Server-to-client request for bidirectional communication */
export interface PlexusStreamItemRequest {
  type: 'request';
  /** Unique identifier for correlating response */
  requestId: string;
  /** Serialized request data */
  requestData: StandardRequest;
  /** Maximum time to wait for response (milliseconds) */
  timeoutMs: number;
}

/** Universal stream item - all activations emit this type */
export type PlexusStreamItem =
  | PlexusStreamItemData
  | PlexusStreamItemProgress
  | PlexusStreamItemError
  | PlexusStreamItemDone
  | PlexusStreamItemRequest;

export function isPlexusStreamItemData(e: PlexusStreamItem): e is PlexusStreamItemData { return e.type === 'data'; }
export function isPlexusStreamItemProgress(e: PlexusStreamItem): e is PlexusStreamItemProgress { return e.type === 'progress'; }
export function isPlexusStreamItemError(e: PlexusStreamItem): e is PlexusStreamItemError { return e.type === 'error'; }
export function isPlexusStreamItemDone(e: PlexusStreamItem): e is PlexusStreamItemDone { return e.type === 'done'; }
export function isPlexusStreamItemRequest(e: PlexusStreamItem): e is PlexusStreamItemRequest { return e.type === 'request'; }

// === Bidirectional Communication Types ===

/** Confirmation request (yes/no) */
export interface StandardRequestConfirm {
  type: 'confirm';
  /** Message to display to user */
  message: string;
  /** Default value if user doesn't respond */
  default?: boolean;
}

/** Text prompt request */
export interface StandardRequestPrompt {
  type: 'prompt';
  /** Message to display to user */
  message: string;
  /** Default value */
  default?: string;
  /** Placeholder text */
  placeholder?: string;
}

/** Selection request (single or multiple choice) */
export interface StandardRequestSelect {
  type: 'select';
  /** Message to display to user */
  message: string;
  /** Available options */
  options: SelectOption[];
  /** Allow multiple selections */
  multiSelect?: boolean;
}

/** Standard request types for common UI patterns */
export type StandardRequest =
  | StandardRequestConfirm
  | StandardRequestPrompt
  | StandardRequestSelect;

export function isStandardRequestConfirm(e: StandardRequest): e is StandardRequestConfirm { return e.type === 'confirm'; }
export function isStandardRequestPrompt(e: StandardRequest): e is StandardRequestPrompt { return e.type === 'prompt'; }
export function isStandardRequestSelect(e: StandardRequest): e is StandardRequestSelect { return e.type === 'select'; }

/** Option in a select menu */
export interface SelectOption {
  /** Value returned when selected */
  value: string;
  /** Display label */
  label: string;
  /** Optional description */
  description?: string;
}

/** Response to confirmation request */
export interface StandardResponseConfirmed {
  type: 'confirmed';
  value: boolean;
}

/** Response to prompt request */
export interface StandardResponseText {
  type: 'text';
  value: string;
}

/** Response to select request */
export interface StandardResponseSelected {
  type: 'selected';
  values: string[];
}

/** User cancelled the request */
export interface StandardResponseCancelled {
  type: 'cancelled';
}

/** Standard response types for bidirectional requests */
export type StandardResponse =
  | StandardResponseConfirmed
  | StandardResponseText
  | StandardResponseSelected
  | StandardResponseCancelled;

export function isStandardResponseConfirmed(e: StandardResponse): e is StandardResponseConfirmed { return e.type === 'confirmed'; }
export function isStandardResponseText(e: StandardResponse): e is StandardResponseText { return e.type === 'text'; }
export function isStandardResponseSelected(e: StandardResponse): e is StandardResponseSelected { return e.type === 'selected'; }
export function isStandardResponseCancelled(e: StandardResponse): e is StandardResponseCancelled { return e.type === 'cancelled'; }

/** Respond to a bidirectional request */
export interface PlexusResponse {
  requestId: string;
  response: StandardResponse;
}

/** Error thrown when a PlexusStreamItemError is received */
export class PlexusError extends Error {
  readonly code: string | undefined;
  readonly recoverable: boolean;
  readonly metadata: StreamMetadata | undefined;
  constructor(
    message: string,
    code?: string,
    recoverable: boolean = false,
    metadata?: StreamMetadata
  ) {
    super(message);
    this.name = 'PlexusError';
    this.code = code;
    this.recoverable = recoverable;
    this.metadata = metadata;
  }
}

// === CA-2: typed authorization errors ===
//
// The server delivers dispatch-time auth failures as stream error items on
// the accepted subscription (plexus-core's `<backend>.call` handler maps
// `PlexusError` to a stream item carrying the semantic JSON-RPC code as a
// string):
//   "-32001"  Unauthenticated — no/invalid session
//   "-32003"  Forbidden — authenticated but not authorized (e.g. the R-5
//             scope gate: "Forbidden: missing required scope '<scope>'")

/**
 * Authenticated but not authorized (stream error code "-32003").
 *
 * When the denial came from the scope gate, `missingScope` carries the
 * unmet scope parsed from the server message
 * (`Forbidden: missing required scope '<scope>'`).
 */
export class ForbiddenError extends PlexusError {
  readonly missingScope: string | undefined;
  constructor(
    message: string,
    recoverable: boolean = false,
    metadata?: StreamMetadata
  ) {
    super(message, '-32003', recoverable, metadata);
    this.name = 'ForbiddenError';
    const m = /missing required scope '([^']+)'/.exec(message);
    this.missingScope = m ? m[1] : undefined;
  }
}

/** No/invalid session where one was required (stream error code "-32001"). */
export class UnauthenticatedError extends PlexusError {
  constructor(
    message: string,
    recoverable: boolean = false,
    metadata?: StreamMetadata
  ) {
    super(message, '-32001', recoverable, metadata);
    this.name = 'UnauthenticatedError';
  }
}

/**
 * Construct the appropriate typed error for a stream error item (CA-2).
 * Falls back to plain PlexusError for codes without a dedicated class.
 */
export function errorFromStreamItem(item: {
  message: string;
  code?: string;
  recoverable: boolean;
  metadata?: StreamMetadata;
}): PlexusError {
  switch (item.code) {
    case '-32003': return new ForbiddenError(item.message, item.recoverable, item.metadata);
    case '-32001': return new UnauthenticatedError(item.message, item.recoverable, item.metadata);
    default:       return new PlexusError(item.message, item.code, item.recoverable, item.metadata);
  }
}
"#.to_string()
}

/// Collect all RefNamed type references from the IR
#[allow(dead_code)]
fn collect_all_referenced_types(ir: &IR) -> HashSet<String> {
    let mut refs = HashSet::new();

    fn collect_from_type_ref(tr: &TypeRef, refs: &mut HashSet<String>) {
        match tr {
            TypeRef::RefNamed(qn) => {
                refs.insert(qn.full_name());
            }
            TypeRef::RefArray(inner) => collect_from_type_ref(inner, refs),
            TypeRef::RefOptional(inner) => collect_from_type_ref(inner, refs),
            _ => {}
        }
    }

    fn collect_from_fields(fields: &[FieldDef], refs: &mut HashSet<String>) {
        for field in fields {
            collect_from_type_ref(&field.fd_type, refs);
        }
    }

    // Collect from all method params and returns
    for method in ir.ir_methods.values() {
        collect_from_type_ref(&method.md_returns, &mut refs);
        for param in &method.md_params {
            collect_from_type_ref(&param.pd_type, &mut refs);
        }
    }

    // Collect from all type definitions (nested refs)
    for typedef in ir.ir_types.values() {
        match &typedef.td_kind {
            TypeKind::KindStruct { ks_fields } => {
                collect_from_fields(ks_fields, &mut refs);
            }
            TypeKind::KindEnum { ke_variants, .. } => {
                for variant in ke_variants {
                    collect_from_fields(&variant.vd_fields, &mut refs);
                }
            }
            TypeKind::KindAlias { ka_target } => {
                collect_from_type_ref(ka_target, &mut refs);
            }
            TypeKind::KindPrimitive { .. } => {}
            TypeKind::KindStringEnum { .. } => {}
        }
    }

    refs
}

/// Generate TypeScript protocol types without any IR content.
/// Used by transport-only generation — no backend connection needed.
pub fn generate_protocol_types() -> String {
    let mut lines = vec![
        "// Auto-generated by hub-codegen — Plexus protocol types".to_string(),
        "// DO NOT EDIT MANUALLY".to_string(),
        "".to_string(),
    ];
    lines.push(generate_core_transport_types());
    lines.join("\n")
}

/// Generate TypeScript core transport types only
/// Domain types are generated in namespace-specific files
pub fn generate_types(ir: &IR) -> String {
    let mut lines = generate_header_comment(ir);
    lines.push("".to_string());
    lines.push(generate_core_transport_types());
    lines.push("".to_string());
    lines.push("// Domain types are exported from their respective namespace modules".to_string());
    lines.push("// Import as: import { TypeName } from './namespace/types'".to_string());

    lines.join("\n")
}

/// Calculate relative import path between two namespaces
/// e.g., from "hyperforge.workspace.repos" to "io" → "../../../io"
fn calculate_relative_import_path(from_namespace: &str, to_namespace: &str) -> String {
    let from_depth = from_namespace.matches('.').count();
    let ups = "../".repeat(from_depth + 1);  // +1 because we're in types.ts
    let to_path = to_namespace.replace('.', "/");
    format!("{}{}", ups, to_path)
}

/// Collect cross-namespace type imports needed for a set of type definitions
fn collect_cross_namespace_type_imports(typedefs: &[&TypeDef], current_namespace: &str) -> std::collections::BTreeMap<String, Vec<String>> {
    use std::collections::BTreeMap;

    let mut imports: BTreeMap<String, Vec<String>> = BTreeMap::new();

    fn collect_from_type_ref(
        tr: &TypeRef,
        imports: &mut BTreeMap<String, Vec<String>>,
        current_namespace: &str,
    ) {
        match tr {
            TypeRef::RefNamed(qn) => {
                // Only import if from a DIFFERENT namespace
                if let Some(ns) = qn.namespace() {
                    if ns != current_namespace {
                        imports
                            .entry(ns.to_string())
                            .or_default()
                            .push(to_pascal(qn.local_name()));
                    }
                }
            }
            TypeRef::RefArray(inner) => collect_from_type_ref(inner, imports, current_namespace),
            TypeRef::RefOptional(inner) => collect_from_type_ref(inner, imports, current_namespace),
            _ => {}
        }
    }

    fn collect_from_fields(fields: &[FieldDef], imports: &mut BTreeMap<String, Vec<String>>, current_namespace: &str) {
        for field in fields {
            collect_from_type_ref(&field.fd_type, imports, current_namespace);
        }
    }

    // Collect from all type definitions
    for typedef in typedefs {
        match &typedef.td_kind {
            TypeKind::KindStruct { ks_fields } => {
                collect_from_fields(ks_fields, &mut imports, current_namespace);
            }
            TypeKind::KindEnum { ke_variants, .. } => {
                for variant in ke_variants {
                    collect_from_fields(&variant.vd_fields, &mut imports, current_namespace);
                }
            }
            TypeKind::KindAlias { ka_target } => {
                collect_from_type_ref(ka_target, &mut imports, current_namespace);
            }
            TypeKind::KindPrimitive { .. } => {}
            TypeKind::KindStringEnum { .. } => {}
        }
    }

    // Deduplicate and sort type names within each namespace
    for types in imports.values_mut() {
        types.sort();
        types.dedup();
    }

    imports
}

/// Generate TypeScript types for a specific namespace
/// Types use local names (no namespace prefix) since they're in their own module
pub fn generate_types_for_namespace(
    ir: &IR,
    namespace: &str,
    emit_deprecation: bool,
    warnings: &mut Vec<DeprecationWarning>,
) -> String {
    let mut lines = vec![
        "// Auto-generated by hub-codegen".to_string(),
        "// Do not edit manually".to_string(),
        "".to_string(),
    ];

    // Filter types for this namespace
    let mut namespace_types: Vec<_> = ir.ir_types.values()
        .filter(|td| td.td_namespace == namespace)
        .collect();

    // Sort for deterministic output
    namespace_types.sort_by(|a, b| a.td_name.cmp(&b.td_name));

    // Collect cross-namespace type imports
    let cross_ns_imports = collect_cross_namespace_type_imports(&namespace_types, namespace);

    // Add cross-namespace imports
    for (other_ns, types) in cross_ns_imports {
        let relative_path = calculate_relative_import_path(namespace, &other_ns);
        let import_line = format!(
            "import type {{ {} }} from '{}/types';",
            types.join(", "),
            relative_path
        );
        lines.push(import_line);
    }

    if !lines.last().map(|s| s.is_empty()).unwrap_or(false) {
        lines.push("".to_string());
    }

    let namespace_path = namespace.replace('.', "/");
    let file_path = format!("{}/types.ts", namespace_path);
    for typedef in namespace_types {
        lines.push(generate_typedef_in_namespace_annotated(
            typedef,
            namespace,
            emit_deprecation,
            &file_path,
            warnings,
        ));
        lines.push("".to_string());
    }

    // Generate stubs for missing types referenced in this namespace
    let missing_stubs = collect_missing_types_for_namespace(ir, namespace);
    if !missing_stubs.is_empty() {
        lines.push("// === Stub Types (referenced but not defined in schema) ===".to_string());
        lines.push("".to_string());

        for local_name in missing_stubs {
            lines.push(format!("/** Stub type - definition missing from IR */"));
            lines.push(format!("export type {} = unknown;", to_pascal(&local_name)));
            lines.push("".to_string());
        }
    }

    lines.join("\n")
}

/// Collect types that are referenced in a namespace but not defined
fn collect_missing_types_for_namespace(ir: &IR, namespace: &str) -> Vec<String> {
    use std::collections::HashSet;

    let mut referenced = HashSet::new();
    let mut defined = HashSet::new();

    // Collect defined types in this namespace
    for (_qual_name, typedef) in &ir.ir_types {
        if typedef.td_namespace == namespace {
            defined.insert(typedef.td_name.clone());
        }
    }

    // Collect types referenced by methods in this namespace
    fn collect_from_type_ref(tr: &TypeRef, namespace: &str, refs: &mut HashSet<String>) {
        match tr {
            TypeRef::RefNamed(qn) => {
                // Only track references within the same namespace
                if qn.namespace() == Some(namespace) {
                    refs.insert(qn.local_name().to_string());
                }
            }
            TypeRef::RefArray(inner) => collect_from_type_ref(inner, namespace, refs),
            TypeRef::RefOptional(inner) => collect_from_type_ref(inner, namespace, refs),
            _ => {}
        }
    }

    for method in ir.ir_methods.values() {
        if method.md_namespace == namespace {
            collect_from_type_ref(&method.md_returns, namespace, &mut referenced);
            for param in &method.md_params {
                collect_from_type_ref(&param.pd_type, namespace, &mut referenced);
            }
        }
    }

    // Find missing = referenced - defined
    let mut missing: Vec<_> = referenced.difference(&defined).cloned().collect();
    missing.sort();
    missing
}

/// Generate namespace type files, optionally restricted to a set of namespaces.
///
/// `filter`: when `Some`, only namespaces that equal or are prefixed by an entry
/// are generated.  `None` generates all namespaces (original behaviour).
pub fn generate_namespace_types(
    ir: &IR,
    filter: Option<&[String]>,
    emit_deprecation: bool,
    warnings: &mut Vec<DeprecationWarning>,
) -> HashMap<String, String> {
    let mut files = HashMap::new();

    // Get unique namespaces from types
    let mut namespaces: HashSet<_> = ir.ir_types.values()
        .map(|td| td.td_namespace.as_str())
        .collect();

    // Also include namespaces that declare no types but whose methods reference
    // a same-namespace named type with no TypeDef (a schema gap). Without this,
    // client.ts emits `import ... from './types'` for those referenced names
    // while no types.ts is ever written → tsc TS2307 (DEFECT). Emitting the file
    // here lets the existing stub path fill in `export type X = unknown;`, so both
    // the import resolves and the symbol exists.
    for method in ir.ir_methods.values() {
        let ns = method.md_namespace.as_str();
        if ns.is_empty() || namespaces.contains(ns) {
            continue;
        }
        if !collect_missing_types_for_namespace(ir, ns).is_empty() {
            namespaces.insert(ns);
        }
    }

    // Sort for deterministic warning order.
    let mut sorted_ns: Vec<_> = namespaces.into_iter().collect();
    sorted_ns.sort();

    for namespace in sorted_ns {
        // Skip empty namespace — those types live in global types.ts
        if namespace.is_empty() {
            continue;
        }

        // Skip namespaces that don't match the filter
        if let Some(f) = filter {
            if !ns_matches_filter(namespace, f) {
                continue;
            }
        }

        let content = generate_types_for_namespace(ir, namespace, emit_deprecation, warnings);
        // Convert dotted namespace to directory path: "hyperforge.workspace.repos" → "hyperforge/workspace/repos"
        let path = namespace.replace('.', "/");
        files.insert(format!("{}/types.ts", path), content);
    }

    files
}

/// Returns true if `namespace` equals any filter entry or is a child of one.
/// E.g. filter=["solar.earth"] matches "solar.earth" and "solar.earth.luna"
///      but not "solar.jupiter".
fn ns_matches_filter(namespace: &str, filter: &[String]) -> bool {
    filter.iter().any(|f| f == namespace || namespace.starts_with(&format!("{f}.")))
}

fn generate_typedef_in_namespace(typedef: &TypeDef, namespace: &str) -> String {
    match &typedef.td_kind {
        TypeKind::KindStruct { ks_fields } => {
            generate_interface_in_ns(&typedef.td_name, ks_fields, &typedef.td_description, namespace, false, None, "", &mut Vec::new())
        }
        TypeKind::KindEnum { ke_discriminator, ke_variants } => {
            generate_union_in_ns(&typedef.td_name, ke_discriminator, ke_variants, &typedef.td_description, namespace)
        }
        TypeKind::KindAlias { ka_target } => {
            generate_alias_in_ns(&typedef.td_name, ka_target, &typedef.td_description, namespace)
        }
        TypeKind::KindPrimitive { kp_type, kp_format } => {
            generate_primitive_alias(&typedef.td_name, kp_type, kp_format.as_deref(), &typedef.td_description)
        }
        TypeKind::KindStringEnum { kse_values } => {
            generate_string_enum(&typedef.td_name, kse_values, &typedef.td_description)
        }
    }
}

/// IR-7: annotated variant — emits deprecation prefix lines above the
/// generated declaration when the typedef (or any of its fields) is
/// deprecated, and records a warning entry.
fn generate_typedef_in_namespace_annotated(
    typedef: &TypeDef,
    namespace: &str,
    emit_deprecation: bool,
    file_path: &str,
    warnings: &mut Vec<DeprecationWarning>,
) -> String {
    let prefix = if emit_deprecation {
        if let Some(info) = &typedef.td_deprecation {
            warnings.push(DeprecationWarning {
                kind: "type".into(),
                name: typedef.full_name(),
                file: file_path.into(),
                message: info.message.clone(),
                since: info.since.clone(),
                removed_in: info.removed_in.clone(),
            });
            let mut p = deprecation::format_ts(info);
            p.push(String::new());
            p.join("\n") + "\n"
        } else {
            String::new()
        }
    } else {
        String::new()
    };

    // For structs, route through the annotated interface emitter so field-
    // level deprecation annotations land in the output; other kinds don't
    // currently carry field-level deprecation in the IR.
    let body = match &typedef.td_kind {
        TypeKind::KindStruct { ks_fields } => generate_interface_in_ns(
            &typedef.td_name,
            ks_fields,
            &typedef.td_description,
            namespace,
            emit_deprecation,
            Some(&typedef.full_name()),
            file_path,
            warnings,
        ),
        _ => generate_typedef_in_namespace(typedef, namespace),
    };

    format!("{}{}", prefix, body)
}

fn generate_interface_in_ns(
    name: &str,
    fields: &[FieldDef],
    desc: &Option<String>,
    namespace: &str,
    emit_deprecation: bool,
    typedef_full_name: Option<&str>,
    file_path: &str,
    warnings: &mut Vec<DeprecationWarning>,
) -> String {
    let mut lines = Vec::new();

    if let Some(d) = desc {
        lines.push(format!("/** {} */", d));
    }

    lines.push(format!("export interface {} {{", to_pascal(name)));

    for field in fields {
        let optional = if field.fd_required { "" } else { "?" };
        let ts_type = field.fd_type.to_ts_in_namespace(namespace);
        if emit_deprecation {
            if let Some(info) = &field.fd_deprecation {
                warnings.push(DeprecationWarning {
                    kind: "field".into(),
                    name: typedef_full_name
                        .map(|t| format!("{}.{}", t, field.fd_name))
                        .unwrap_or_else(|| field.fd_name.clone()),
                    file: file_path.into(),
                    message: info.message.clone(),
                    since: info.since.clone(),
                    removed_in: info.removed_in.clone(),
                });
                for line in deprecation::format_ts(info) {
                    lines.push(format!("  {}", line));
                }
            }
        }
        if let Some(d) = &field.fd_description {
            lines.push(format!("  /** {} */", d));
        }
        lines.push(format!("  {}{}: {};", to_camel(&field.fd_name), optional, ts_type));
    }

    lines.push("}".to_string());
    lines.join("\n")
}

fn generate_union_in_ns(
    name: &str,
    discriminator: &str,
    variants: &[VariantDef],
    desc: &Option<String>,
    namespace: &str,
) -> String {
    let pascal_name = to_pascal(name);
    let mut lines = Vec::new();

    // Flat variant interface names: TypeNameVariantName
    let flat_variant_names: Vec<String> = variants
        .iter()
        .map(|v| format!("{}{}", pascal_name, to_pascal(&v.vd_name)))
        .collect();

    // Emit each variant interface as a top-level export first
    for (i, variant) in variants.iter().enumerate() {
        let flat_name = &flat_variant_names[i];

        if let Some(d) = &variant.vd_description {
            lines.push(format!("/** {} */", d));
        }
        lines.push(format!("export interface {} {{", flat_name));
        lines.push(format!("  {}: '{}';", discriminator, variant.vd_name));

        for field in &variant.vd_fields {
            let optional = if field.fd_required { "" } else { "?" };
            let ts_type = field.fd_type.to_ts_in_namespace(namespace);
            if let Some(d) = &field.fd_description {
                lines.push(format!("  /** {} */", d));
            }
            lines.push(format!("  {}{}: {};", to_camel(&field.fd_name), optional, ts_type));
        }

        lines.push("}".to_string());
        lines.push("".to_string());
    }

    // Only use the first paragraph of the description (strip Rust impl notes)
    if let Some(d) = desc {
        let first_para = d.split("\n\n").next().unwrap_or(d).trim();
        if !first_para.is_empty() {
            lines.push(format!("/** {} */", first_para));
        }
    }

    // Union type referencing flat names
    let union_type = if flat_variant_names.is_empty() {
        "never".to_string()
    } else {
        flat_variant_names.join(" | ")
    };

    lines.push(format!("export type {} = {};", pascal_name, union_type));

    // Top-level type guard functions
    if !variants.is_empty() {
        lines.push("".to_string());
        for (i, variant) in variants.iter().enumerate() {
            let flat_name = &flat_variant_names[i];
            lines.push(format!(
                "export function is{}(e: {}): e is {} {{ return e.{} === '{}'; }}",
                flat_name, pascal_name, flat_name, discriminator, variant.vd_name
            ));
        }
    }

    lines.join("\n")
}

fn generate_alias_in_ns(name: &str, target: &TypeRef, desc: &Option<String>, namespace: &str) -> String {
    let mut lines = Vec::new();
    if let Some(d) = desc {
        lines.push(format!("/** {} */", d));
    }
    lines.push(format!("export type {} = {};", to_pascal(name), target.to_ts_in_namespace(namespace)));
    lines.join("\n")
}

#[allow(dead_code)]
fn generate_typedef(typedef: &TypeDef) -> String {
    match &typedef.td_kind {
        TypeKind::KindStruct { ks_fields } => {
            generate_interface(&typedef.td_name, ks_fields, &typedef.td_description)
        }
        TypeKind::KindEnum { ke_discriminator, ke_variants } => {
            generate_discriminated_union(&typedef.td_name, ke_discriminator, ke_variants, &typedef.td_description)
        }
        TypeKind::KindAlias { ka_target } => {
            generate_alias(&typedef.td_name, ka_target, &typedef.td_description)
        }
        TypeKind::KindPrimitive { kp_type, kp_format } => {
            generate_primitive_alias(&typedef.td_name, kp_type, kp_format.as_deref(), &typedef.td_description)
        }
        TypeKind::KindStringEnum { kse_values } => {
            generate_string_enum(&typedef.td_name, kse_values, &typedef.td_description)
        }
    }
}

#[allow(dead_code)]
fn generate_interface(name: &str, fields: &[FieldDef], desc: &Option<String>) -> String {
    let mut lines = Vec::new();

    if let Some(d) = desc {
        lines.push(format!("/** {} */", d));
    }

    lines.push(format!("export interface {} {{", to_pascal(name)));

    for field in fields {
        let optional = if field.fd_required { "" } else { "?" };
        let ts_type = field.fd_type.to_ts();
        if let Some(d) = &field.fd_description {
            lines.push(format!("  /** {} */", d));
        }
        lines.push(format!("  {}{}: {};", to_camel(&field.fd_name), optional, ts_type));
    }

    lines.push("}".to_string());
    lines.join("\n")
}

#[allow(dead_code)]
fn generate_discriminated_union(
    name: &str,
    discriminator: &str,
    variants: &[VariantDef],
    desc: &Option<String>,
) -> String {
    let mut lines = Vec::new();

    if let Some(d) = desc {
        lines.push(format!("/** {} */", d));
    }

    // Generate union type
    let variant_names: Vec<String> = variants
        .iter()
        .map(|v| format!("{}_{}", to_pascal(name), to_pascal(&v.vd_name)))
        .collect();

    // Handle empty variants - use `never` type for enums with no variants
    let union_type = if variant_names.is_empty() {
        "never".to_string()
    } else {
        variant_names.join(" | ")
    };

    lines.push(format!(
        "export type {} = {};",
        to_pascal(name),
        union_type
    ));
    lines.push("".to_string());

    // Generate individual variant interfaces
    for variant in variants {
        let variant_type_name = format!("{}_{}", to_pascal(name), to_pascal(&variant.vd_name));

        if let Some(d) = &variant.vd_description {
            lines.push(format!("/** {} */", d));
        }
        lines.push(format!("export interface {} {{", variant_type_name));
        lines.push(format!("  {}: '{}';", discriminator, variant.vd_name));

        for field in &variant.vd_fields {
            let optional = if field.fd_required { "" } else { "?" };
            let ts_type = field.fd_type.to_ts();
            if let Some(d) = &field.fd_description {
                lines.push(format!("  /** {} */", d));
            }
            lines.push(format!("  {}{}: {};", to_camel(&field.fd_name), optional, ts_type));
        }

        lines.push("}".to_string());
        lines.push("".to_string());
    }

    lines.join("\n")
}

#[allow(dead_code)]
fn generate_alias(name: &str, target: &crate::ir::TypeRef, desc: &Option<String>) -> String {
    let mut lines = Vec::new();
    if let Some(d) = desc {
        lines.push(format!("/** {} */", d));
    }
    lines.push(format!("export type {} = {};", to_pascal(name), target.to_ts()));
    lines.join("\n")
}

fn generate_primitive_alias(
    name: &str,
    prim_type: &str,
    format: Option<&str>,
    desc: &Option<String>,
) -> String {
    let mut lines = Vec::new();
    if let Some(d) = desc {
        lines.push(format!("/** {} */", d));
    }
    let ts_type = match (prim_type, format) {
        ("string", Some("uuid")) => "string",
        ("string", _) => "string",
        ("integer", _) | ("number", _) => "number",
        ("boolean", _) => "boolean",
        _ => "unknown",
    };
    lines.push(format!("export type {} = {};", to_pascal(name), ts_type));
    lines.join("\n")
}

fn generate_string_enum(name: &str, values: &[String], desc: &Option<String>) -> String {
    let mut lines = Vec::new();
    if let Some(d) = desc {
        lines.push(format!("/** {} */", d));
    }
    // Generate TypeScript string literal union: type Foo = "a" | "b" | "c";
    let union_values: Vec<String> = values.iter().map(|v| format!("\"{}\"", v)).collect();
    let union_type = if union_values.is_empty() {
        "never".to_string()
    } else {
        union_values.join(" | ")
    };
    lines.push(format!("export type {} = {};", to_pascal(name), union_type));
    lines.join("\n")
}

/// Convert to PascalCase
fn to_pascal(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize = true;
    for c in s.chars() {
        if c == '_' || c == '-' || c == '.' {  // Treat dots as word boundaries
            capitalize = true;
        } else if capitalize {
            result.push(c.to_ascii_uppercase());
            capitalize = false;
        } else {
            result.push(c);
        }
    }
    result
}

/// Convert to camelCase
fn to_camel(s: &str) -> String {
    let pascal = to_pascal(s);
    if pascal.is_empty() {
        return pascal;
    }
    let mut chars = pascal.chars();
    match chars.next() {
        Some(first) => first.to_ascii_lowercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}
