//! Code generation from IR

pub mod types;
pub mod namespaces;
pub mod rpc;
pub mod transport;
pub mod package;
pub mod tests;

use crate::ir::IR;
use anyhow::Result;
use std::collections::HashMap;

/// A warning emitted during code generation
#[derive(Debug, Clone)]
pub struct Warning {
    pub location: String,
    pub message: String,
}

impl std::fmt::Display for Warning {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}: {}", self.location, self.message)
    }
}

/// Result of code generation
pub struct GenerationResult {
    /// Map of relative path -> file content
    pub files: HashMap<String, String>,
    /// Warnings encountered during generation
    pub warnings: Vec<Warning>,
}

/// Generate TypeScript code from IR
pub fn generate(ir: &IR) -> Result<GenerationResult> {
    let mut files = HashMap::new();
    let mut warnings = Vec::new();

    // Collect warnings for unknown types
    collect_warnings(ir, &mut warnings);

    // Generate types (includes PlexusStreamItem and domain types)
    let types_content = types::generate_types(ir);
    files.insert("types.ts".to_string(), types_content);

    // Generate RPC client interface (Layer 1)
    let rpc_content = rpc::generate_rpc_client();
    files.insert("rpc.ts".to_string(), rpc_content);

    // Generate namespace interfaces with typed client implementations (Layer 2)
    let namespace_files = namespaces::generate_namespaces(ir);
    files.extend(namespace_files);

    // Generate WebSocket transport implementation (Layer 1 implementation)
    let transport_content = transport::generate_transport();
    files.insert("transport.ts".to_string(), transport_content);

    // Generate index
    let index = generate_index(ir);
    files.insert("index.ts".to_string(), index);

    // Generate package.json
    let package_json = package::generate_package_json(ir);
    files.insert("package.json".to_string(), package_json);

    // Generate tsconfig.json
    let tsconfig = package::generate_tsconfig();
    files.insert("tsconfig.json".to_string(), tsconfig);

    // Generate smoke test
    let smoke_test = tests::generate_smoke_test();
    files.insert("test/smoke.test.ts".to_string(), smoke_test);

    Ok(GenerationResult { files, warnings })
}

/// Collect warnings for unknown/untyped references
///
/// Only warns on RefUnknown (schema gaps), NOT on RefAny (intentionally dynamic)
fn collect_warnings(ir: &IR, warnings: &mut Vec<Warning>) {
    use crate::ir::TypeKind;

    // Check method return types and params
    for (path, method) in &ir.ir_methods {
        if method.md_returns.is_unknown() {
            warnings.push(Warning {
                location: path.clone(),
                message: "return type is unknown (missing schema)".to_string(),
            });
        }

        for param in &method.md_params {
            if param.pd_type.is_unknown() {
                warnings.push(Warning {
                    location: format!("{}({})", path, param.pd_name),
                    message: "parameter type is unknown (missing schema)".to_string(),
                });
            }
        }
    }

    // Check type definitions for unknown field types
    for (name, typedef) in &ir.ir_types {
        match &typedef.td_kind {
            TypeKind::KindStruct { ks_fields } => {
                for field in ks_fields {
                    if field.fd_type.contains_unknown() {
                        warnings.push(Warning {
                            location: format!("{}.{}", name, field.fd_name),
                            message: "field type contains unknown (missing schema)".to_string(),
                        });
                    }
                }
            }
            TypeKind::KindEnum { ke_variants, .. } => {
                for variant in ke_variants {
                    for field in &variant.vd_fields {
                        if field.fd_type.contains_unknown() {
                            warnings.push(Warning {
                                location: format!("{}.{}.{}", name, variant.vd_name, field.fd_name),
                                message: "field type contains unknown (missing schema)".to_string(),
                            });
                        }
                    }
                }
            }
            _ => {}
        }
    }
}

fn generate_index(ir: &IR) -> String {
    let mut lines = vec![
        "// Auto-generated by hub-codegen".to_string(),
        "".to_string(),
        "// Core types".to_string(),
        "export * from './types';".to_string(),
        "".to_string(),
        "// RPC client interface (Layer 1)".to_string(),
        "export * from './rpc';".to_string(),
        "".to_string(),
        "// WebSocket transport (Layer 1 implementation)".to_string(),
        "export * from './transport';".to_string(),
        "".to_string(),
        "// Typed client interfaces (Layer 2)".to_string(),
    ];

    // Get unique namespaces
    let mut namespaces: Vec<_> = ir.ir_plugins.keys().collect();
    namespaces.sort();

    for namespace in namespaces {
        lines.push(format!("export * from './{}'", namespace));
    }

    lines.join("\n")
}
