//! Type generation

use crate::ir::{IR, TypeDef, TypeKind, FieldDef, VariantDef};

/// Generate PlexusStreamItem and StreamMetadata - the core transport types
fn generate_core_transport_types() -> String {
    r#"// === Core Transport Types ===
// These types define the wire format for all plexus streaming responses.

/** Metadata applied by the caller when wrapping activation responses */
export interface StreamMetadata {
  /** Call path through the system (e.g., ["plexus", "health"]) */
  provenance: string[];
  /** Hash of plexus configuration for cache invalidation */
  plexusHash: string;
  /** Unix timestamp (seconds) when the event was wrapped */
  timestamp: number;
}

/** Universal stream item - all activations emit this type */
export type PlexusStreamItem =
  | PlexusStreamItem_Data
  | PlexusStreamItem_Progress
  | PlexusStreamItem_Error
  | PlexusStreamItem_Done;

/** Data payload with caller-applied metadata */
export interface PlexusStreamItem_Data {
  type: 'data';
  /** Metadata from calling layer */
  metadata: StreamMetadata;
  /** Type identifier for deserialization (e.g., "health.status") */
  contentType: string;
  /** The actual payload (serialized activation event) */
  content: unknown;
}

/** Progress update during long-running operations */
export interface PlexusStreamItem_Progress {
  type: 'progress';
  /** Metadata from calling layer */
  metadata: StreamMetadata;
  /** Human-readable progress message */
  message: string;
  /** Optional completion percentage (0.0 - 100.0) */
  percentage?: number;
}

/** Error occurred during processing */
export interface PlexusStreamItem_Error {
  type: 'error';
  /** Metadata from calling layer */
  metadata: StreamMetadata;
  /** Human-readable error message */
  message: string;
  /** Optional error code for programmatic handling */
  code?: string;
  /** Whether the operation can be retried */
  recoverable: boolean;
}

/** Stream completed successfully */
export interface PlexusStreamItem_Done {
  type: 'done';
  /** Metadata from calling layer */
  metadata: StreamMetadata;
}

/** Error thrown when a PlexusStreamItem_Error is received */
export class PlexusError extends Error {
  constructor(
    message: string,
    public readonly code?: string,
    public readonly recoverable: boolean = false,
    public readonly metadata?: StreamMetadata
  ) {
    super(message);
    this.name = 'PlexusError';
  }
}
"#.to_string()
}

/// Generate TypeScript types from IR
pub fn generate_types(ir: &IR) -> String {
    let mut lines = vec![
        "// Auto-generated by hub-codegen".to_string(),
        "// Do not edit manually".to_string(),
        "".to_string(),
        generate_core_transport_types(),
        "// === Domain Types ===".to_string(),
        "".to_string(),
    ];

    // Sort types for deterministic output
    let mut type_names: Vec<_> = ir.ir_types.keys().collect();
    type_names.sort();

    for name in type_names {
        let typedef = &ir.ir_types[name];
        lines.push(generate_typedef(typedef));
        lines.push("".to_string());
    }

    lines.join("\n")
}

fn generate_typedef(typedef: &TypeDef) -> String {
    match &typedef.td_kind {
        TypeKind::KindStruct { ks_fields } => {
            generate_interface(&typedef.td_name, ks_fields, &typedef.td_description)
        }
        TypeKind::KindEnum { ke_discriminator, ke_variants } => {
            generate_discriminated_union(&typedef.td_name, ke_discriminator, ke_variants, &typedef.td_description)
        }
        TypeKind::KindAlias { ka_target } => {
            generate_alias(&typedef.td_name, ka_target, &typedef.td_description)
        }
        TypeKind::KindPrimitive { kp_type, kp_format } => {
            generate_primitive_alias(&typedef.td_name, kp_type, kp_format.as_deref(), &typedef.td_description)
        }
    }
}

fn generate_interface(name: &str, fields: &[FieldDef], desc: &Option<String>) -> String {
    let mut lines = Vec::new();

    if let Some(d) = desc {
        lines.push(format!("/** {} */", d));
    }

    lines.push(format!("export interface {} {{", to_pascal(name)));

    for field in fields {
        let optional = if field.fd_required { "" } else { "?" };
        let ts_type = field.fd_type.to_ts();
        if let Some(d) = &field.fd_description {
            lines.push(format!("  /** {} */", d));
        }
        lines.push(format!("  {}{}: {};", to_camel(&field.fd_name), optional, ts_type));
    }

    lines.push("}".to_string());
    lines.join("\n")
}

fn generate_discriminated_union(
    name: &str,
    discriminator: &str,
    variants: &[VariantDef],
    desc: &Option<String>,
) -> String {
    let mut lines = Vec::new();

    if let Some(d) = desc {
        lines.push(format!("/** {} */", d));
    }

    // Generate union type
    let variant_names: Vec<String> = variants
        .iter()
        .map(|v| format!("{}_{}", to_pascal(name), to_pascal(&v.vd_name)))
        .collect();

    lines.push(format!(
        "export type {} = {};",
        to_pascal(name),
        variant_names.join(" | ")
    ));
    lines.push("".to_string());

    // Generate individual variant interfaces
    for variant in variants {
        let variant_type_name = format!("{}_{}", to_pascal(name), to_pascal(&variant.vd_name));

        if let Some(d) = &variant.vd_description {
            lines.push(format!("/** {} */", d));
        }
        lines.push(format!("export interface {} {{", variant_type_name));
        lines.push(format!("  {}: '{}';", discriminator, variant.vd_name));

        for field in &variant.vd_fields {
            let optional = if field.fd_required { "" } else { "?" };
            let ts_type = field.fd_type.to_ts();
            if let Some(d) = &field.fd_description {
                lines.push(format!("  /** {} */", d));
            }
            lines.push(format!("  {}{}: {};", to_camel(&field.fd_name), optional, ts_type));
        }

        lines.push("}".to_string());
        lines.push("".to_string());
    }

    lines.join("\n")
}

fn generate_alias(name: &str, target: &crate::ir::TypeRef, desc: &Option<String>) -> String {
    let mut lines = Vec::new();
    if let Some(d) = desc {
        lines.push(format!("/** {} */", d));
    }
    lines.push(format!("export type {} = {};", to_pascal(name), target.to_ts()));
    lines.join("\n")
}

fn generate_primitive_alias(
    name: &str,
    prim_type: &str,
    format: Option<&str>,
    desc: &Option<String>,
) -> String {
    let mut lines = Vec::new();
    if let Some(d) = desc {
        lines.push(format!("/** {} */", d));
    }
    let ts_type = match (prim_type, format) {
        ("string", Some("uuid")) => "string",
        ("string", _) => "string",
        ("integer", _) | ("number", _) => "number",
        ("boolean", _) => "boolean",
        _ => "unknown",
    };
    lines.push(format!("export type {} = {};", to_pascal(name), ts_type));
    lines.join("\n")
}

/// Convert to PascalCase
fn to_pascal(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize = true;
    for c in s.chars() {
        if c == '_' || c == '-' {
            capitalize = true;
        } else if capitalize {
            result.push(c.to_ascii_uppercase());
            capitalize = false;
        } else {
            result.push(c);
        }
    }
    result
}

/// Convert to camelCase
fn to_camel(s: &str) -> String {
    let pascal = to_pascal(s);
    if pascal.is_empty() {
        return pascal;
    }
    let mut chars = pascal.chars();
    match chars.next() {
        Some(first) => first.to_ascii_lowercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}
