//! Type generation

use crate::ir::{IR, TypeDef, TypeKind, TypeRef, FieldDef, VariantDef};
use std::collections::{HashSet, HashMap};

/// Generate PlexusStreamItem and StreamMetadata - the core transport types
fn generate_core_transport_types() -> String {
    r#"// === Core Transport Types ===
// These types define the wire format for all plexus streaming responses.

/** Metadata applied by the caller when wrapping activation responses */
export interface StreamMetadata {
  /** Call path through the system (e.g., ["plexus", "health"]) */
  provenance: string[];
  /** Hash of plexus configuration for cache invalidation */
  plexusHash: string;
  /** Unix timestamp (seconds) when the event was wrapped */
  timestamp: number;
}

/** Universal stream item - all activations emit this type */
export type PlexusStreamItem =
  | PlexusStreamItem_Data
  | PlexusStreamItem_Progress
  | PlexusStreamItem_Error
  | PlexusStreamItem_Done;

/** Data payload with caller-applied metadata */
export interface PlexusStreamItem_Data {
  type: 'data';
  /** Metadata from calling layer */
  metadata: StreamMetadata;
  /** Type identifier for deserialization (e.g., "health.status") */
  contentType: string;
  /** The actual payload (serialized activation event) */
  content: unknown;
}

/** Progress update during long-running operations */
export interface PlexusStreamItem_Progress {
  type: 'progress';
  /** Metadata from calling layer */
  metadata: StreamMetadata;
  /** Human-readable progress message */
  message: string;
  /** Optional completion percentage (0.0 - 100.0) */
  percentage?: number;
}

/** Error occurred during processing */
export interface PlexusStreamItem_Error {
  type: 'error';
  /** Metadata from calling layer */
  metadata: StreamMetadata;
  /** Human-readable error message */
  message: string;
  /** Optional error code for programmatic handling */
  code?: string;
  /** Whether the operation can be retried */
  recoverable: boolean;
}

/** Stream completed successfully */
export interface PlexusStreamItem_Done {
  type: 'done';
  /** Metadata from calling layer */
  metadata: StreamMetadata;
}

/** Error thrown when a PlexusStreamItem_Error is received */
export class PlexusError extends Error {
  constructor(
    message: string,
    public readonly code?: string,
    public readonly recoverable: boolean = false,
    public readonly metadata?: StreamMetadata
  ) {
    super(message);
    this.name = 'PlexusError';
  }
}
"#.to_string()
}

/// Collect all RefNamed type references from the IR
#[allow(dead_code)]
fn collect_all_referenced_types(ir: &IR) -> HashSet<String> {
    let mut refs = HashSet::new();

    fn collect_from_type_ref(tr: &TypeRef, refs: &mut HashSet<String>) {
        match tr {
            TypeRef::RefNamed(qn) => {
                refs.insert(qn.full_name());
            }
            TypeRef::RefArray(inner) => collect_from_type_ref(inner, refs),
            TypeRef::RefOptional(inner) => collect_from_type_ref(inner, refs),
            _ => {}
        }
    }

    fn collect_from_fields(fields: &[FieldDef], refs: &mut HashSet<String>) {
        for field in fields {
            collect_from_type_ref(&field.fd_type, refs);
        }
    }

    // Collect from all method params and returns
    for method in ir.ir_methods.values() {
        collect_from_type_ref(&method.md_returns, &mut refs);
        for param in &method.md_params {
            collect_from_type_ref(&param.pd_type, &mut refs);
        }
    }

    // Collect from all type definitions (nested refs)
    for typedef in ir.ir_types.values() {
        match &typedef.td_kind {
            TypeKind::KindStruct { ks_fields } => {
                collect_from_fields(ks_fields, &mut refs);
            }
            TypeKind::KindEnum { ke_variants, .. } => {
                for variant in ke_variants {
                    collect_from_fields(&variant.vd_fields, &mut refs);
                }
            }
            TypeKind::KindAlias { ka_target } => {
                collect_from_type_ref(ka_target, &mut refs);
            }
            TypeKind::KindPrimitive { .. } => {}
            TypeKind::KindStringEnum { .. } => {}
        }
    }

    refs
}

/// Generate TypeScript core transport types only
/// Domain types are generated in namespace-specific files
pub fn generate_types(_ir: &IR) -> String {
    let lines = vec![
        "// Auto-generated by hub-codegen".to_string(),
        "// Do not edit manually".to_string(),
        "".to_string(),
        generate_core_transport_types(),
        "".to_string(),
        "// Domain types are exported from their respective namespace modules".to_string(),
        "// Import as: import { TypeName } from './namespace/types'".to_string(),
    ];

    lines.join("\n")
}

/// Calculate relative import path between two namespaces
/// e.g., from "hyperforge.workspace.repos" to "io" → "../../../io"
fn calculate_relative_import_path(from_namespace: &str, to_namespace: &str) -> String {
    let from_depth = from_namespace.matches('.').count();
    let ups = "../".repeat(from_depth + 1);  // +1 because we're in types.ts
    let to_path = to_namespace.replace('.', "/");
    format!("{}{}", ups, to_path)
}

/// Collect cross-namespace type imports needed for a set of type definitions
fn collect_cross_namespace_type_imports(typedefs: &[&TypeDef], current_namespace: &str) -> std::collections::BTreeMap<String, Vec<String>> {
    use std::collections::BTreeMap;

    let mut imports: BTreeMap<String, Vec<String>> = BTreeMap::new();

    fn collect_from_type_ref(
        tr: &TypeRef,
        imports: &mut BTreeMap<String, Vec<String>>,
        current_namespace: &str,
    ) {
        match tr {
            TypeRef::RefNamed(qn) => {
                // Only import if from a DIFFERENT namespace
                if let Some(ns) = qn.namespace() {
                    if ns != current_namespace {
                        imports
                            .entry(ns.to_string())
                            .or_default()
                            .push(to_pascal(qn.local_name()));
                    }
                }
            }
            TypeRef::RefArray(inner) => collect_from_type_ref(inner, imports, current_namespace),
            TypeRef::RefOptional(inner) => collect_from_type_ref(inner, imports, current_namespace),
            _ => {}
        }
    }

    fn collect_from_fields(fields: &[FieldDef], imports: &mut BTreeMap<String, Vec<String>>, current_namespace: &str) {
        for field in fields {
            collect_from_type_ref(&field.fd_type, imports, current_namespace);
        }
    }

    // Collect from all type definitions
    for typedef in typedefs {
        match &typedef.td_kind {
            TypeKind::KindStruct { ks_fields } => {
                collect_from_fields(ks_fields, &mut imports, current_namespace);
            }
            TypeKind::KindEnum { ke_variants, .. } => {
                for variant in ke_variants {
                    collect_from_fields(&variant.vd_fields, &mut imports, current_namespace);
                }
            }
            TypeKind::KindAlias { ka_target } => {
                collect_from_type_ref(ka_target, &mut imports, current_namespace);
            }
            TypeKind::KindPrimitive { .. } => {}
            TypeKind::KindStringEnum { .. } => {}
        }
    }

    // Deduplicate and sort type names within each namespace
    for types in imports.values_mut() {
        types.sort();
        types.dedup();
    }

    imports
}

/// Generate TypeScript types for a specific namespace
/// Types use local names (no namespace prefix) since they're in their own module
pub fn generate_types_for_namespace(ir: &IR, namespace: &str) -> String {
    let mut lines = vec![
        "// Auto-generated by hub-codegen".to_string(),
        "// Do not edit manually".to_string(),
        "".to_string(),
    ];

    // Filter types for this namespace
    let mut namespace_types: Vec<_> = ir.ir_types.values()
        .filter(|td| td.td_namespace == namespace)
        .collect();

    // Sort for deterministic output
    namespace_types.sort_by(|a, b| a.td_name.cmp(&b.td_name));

    // Collect cross-namespace type imports
    let cross_ns_imports = collect_cross_namespace_type_imports(&namespace_types, namespace);

    // Add cross-namespace imports
    for (other_ns, types) in cross_ns_imports {
        let relative_path = calculate_relative_import_path(namespace, &other_ns);
        let import_line = format!(
            "import type {{ {} }} from '{}/types';",
            types.join(", "),
            relative_path
        );
        lines.push(import_line);
    }

    if !lines.last().map(|s| s.is_empty()).unwrap_or(false) {
        lines.push("".to_string());
    }

    for typedef in namespace_types {
        lines.push(generate_typedef_in_namespace(typedef, namespace));
        lines.push("".to_string());
    }

    // Generate stubs for missing types referenced in this namespace
    let missing_stubs = collect_missing_types_for_namespace(ir, namespace);
    if !missing_stubs.is_empty() {
        lines.push("// === Stub Types (referenced but not defined in schema) ===".to_string());
        lines.push("".to_string());

        for local_name in missing_stubs {
            lines.push(format!("/** Stub type - definition missing from IR */"));
            lines.push(format!("export type {} = unknown;", to_pascal(&local_name)));
            lines.push("".to_string());
        }
    }

    lines.join("\n")
}

/// Collect types that are referenced in a namespace but not defined
fn collect_missing_types_for_namespace(ir: &IR, namespace: &str) -> Vec<String> {
    use std::collections::HashSet;

    let mut referenced = HashSet::new();
    let mut defined = HashSet::new();

    // Collect defined types in this namespace
    for (_qual_name, typedef) in &ir.ir_types {
        if typedef.td_namespace == namespace {
            defined.insert(typedef.td_name.clone());
        }
    }

    // Collect types referenced by methods in this namespace
    fn collect_from_type_ref(tr: &TypeRef, namespace: &str, refs: &mut HashSet<String>) {
        match tr {
            TypeRef::RefNamed(qn) => {
                // Only track references within the same namespace
                if qn.namespace() == Some(namespace) {
                    refs.insert(qn.local_name().to_string());
                }
            }
            TypeRef::RefArray(inner) => collect_from_type_ref(inner, namespace, refs),
            TypeRef::RefOptional(inner) => collect_from_type_ref(inner, namespace, refs),
            _ => {}
        }
    }

    for method in ir.ir_methods.values() {
        if method.md_namespace == namespace {
            collect_from_type_ref(&method.md_returns, namespace, &mut referenced);
            for param in &method.md_params {
                collect_from_type_ref(&param.pd_type, namespace, &mut referenced);
            }
        }
    }

    // Find missing = referenced - defined
    let mut missing: Vec<_> = referenced.difference(&defined).cloned().collect();
    missing.sort();
    missing
}

/// Generate all namespace type files
pub fn generate_namespace_types(ir: &IR) -> HashMap<String, String> {
    let mut files = HashMap::new();

    // Get unique namespaces from types
    let namespaces: HashSet<_> = ir.ir_types.values()
        .map(|td| td.td_namespace.as_str())
        .collect();

    for namespace in namespaces {
        // Skip empty namespace - those types are in global types.ts
        if namespace.is_empty() {
            continue;
        }

        let content = generate_types_for_namespace(ir, namespace);
        // Convert dotted namespace to directory path: "hyperforge.workspace.repos" → "hyperforge/workspace/repos"
        let path = namespace.replace('.', "/");
        files.insert(format!("{}/types.ts", path), content);
    }

    files
}

fn generate_typedef_in_namespace(typedef: &TypeDef, namespace: &str) -> String {
    match &typedef.td_kind {
        TypeKind::KindStruct { ks_fields } => {
            generate_interface_in_ns(&typedef.td_name, ks_fields, &typedef.td_description, namespace)
        }
        TypeKind::KindEnum { ke_discriminator, ke_variants } => {
            generate_union_in_ns(&typedef.td_name, ke_discriminator, ke_variants, &typedef.td_description, namespace)
        }
        TypeKind::KindAlias { ka_target } => {
            generate_alias_in_ns(&typedef.td_name, ka_target, &typedef.td_description, namespace)
        }
        TypeKind::KindPrimitive { kp_type, kp_format } => {
            generate_primitive_alias(&typedef.td_name, kp_type, kp_format.as_deref(), &typedef.td_description)
        }
        TypeKind::KindStringEnum { kse_values } => {
            generate_string_enum(&typedef.td_name, kse_values, &typedef.td_description)
        }
    }
}

fn generate_interface_in_ns(name: &str, fields: &[FieldDef], desc: &Option<String>, namespace: &str) -> String {
    let mut lines = Vec::new();

    if let Some(d) = desc {
        lines.push(format!("/** {} */", d));
    }

    lines.push(format!("export interface {} {{", to_pascal(name)));

    for field in fields {
        let optional = if field.fd_required { "" } else { "?" };
        let ts_type = field.fd_type.to_ts_in_namespace(namespace);
        if let Some(d) = &field.fd_description {
            lines.push(format!("  /** {} */", d));
        }
        lines.push(format!("  {}{}: {};", to_camel(&field.fd_name), optional, ts_type));
    }

    lines.push("}".to_string());
    lines.join("\n")
}

fn generate_union_in_ns(
    name: &str,
    discriminator: &str,
    variants: &[VariantDef],
    desc: &Option<String>,
    namespace: &str,
) -> String {
    let mut lines = Vec::new();

    if let Some(d) = desc {
        lines.push(format!("/** {} */", d));
    }

    // Generate union type
    let variant_names: Vec<String> = variants
        .iter()
        .map(|v| format!("{}_{}", to_pascal(name), to_pascal(&v.vd_name)))
        .collect();

    let union_type = if variant_names.is_empty() {
        "never".to_string()
    } else {
        variant_names.join(" | ")
    };

    lines.push(format!("export type {} = {};", to_pascal(name), union_type));
    lines.push("".to_string());

    // Generate individual variant interfaces
    for variant in variants {
        let variant_type_name = format!("{}_{}", to_pascal(name), to_pascal(&variant.vd_name));

        if let Some(d) = &variant.vd_description {
            lines.push(format!("/** {} */", d));
        }
        lines.push(format!("export interface {} {{", variant_type_name));
        lines.push(format!("  {}: '{}';", discriminator, variant.vd_name));

        for field in &variant.vd_fields {
            let optional = if field.fd_required { "" } else { "?" };
            let ts_type = field.fd_type.to_ts_in_namespace(namespace);
            if let Some(d) = &field.fd_description {
                lines.push(format!("  /** {} */", d));
            }
            lines.push(format!("  {}{}: {};", to_camel(&field.fd_name), optional, ts_type));
        }

        lines.push("}".to_string());
        lines.push("".to_string());
    }

    lines.join("\n")
}

fn generate_alias_in_ns(name: &str, target: &TypeRef, desc: &Option<String>, namespace: &str) -> String {
    let mut lines = Vec::new();
    if let Some(d) = desc {
        lines.push(format!("/** {} */", d));
    }
    lines.push(format!("export type {} = {};", to_pascal(name), target.to_ts_in_namespace(namespace)));
    lines.join("\n")
}

#[allow(dead_code)]
fn generate_typedef(typedef: &TypeDef) -> String {
    match &typedef.td_kind {
        TypeKind::KindStruct { ks_fields } => {
            generate_interface(&typedef.td_name, ks_fields, &typedef.td_description)
        }
        TypeKind::KindEnum { ke_discriminator, ke_variants } => {
            generate_discriminated_union(&typedef.td_name, ke_discriminator, ke_variants, &typedef.td_description)
        }
        TypeKind::KindAlias { ka_target } => {
            generate_alias(&typedef.td_name, ka_target, &typedef.td_description)
        }
        TypeKind::KindPrimitive { kp_type, kp_format } => {
            generate_primitive_alias(&typedef.td_name, kp_type, kp_format.as_deref(), &typedef.td_description)
        }
        TypeKind::KindStringEnum { kse_values } => {
            generate_string_enum(&typedef.td_name, kse_values, &typedef.td_description)
        }
    }
}

#[allow(dead_code)]
fn generate_interface(name: &str, fields: &[FieldDef], desc: &Option<String>) -> String {
    let mut lines = Vec::new();

    if let Some(d) = desc {
        lines.push(format!("/** {} */", d));
    }

    lines.push(format!("export interface {} {{", to_pascal(name)));

    for field in fields {
        let optional = if field.fd_required { "" } else { "?" };
        let ts_type = field.fd_type.to_ts();
        if let Some(d) = &field.fd_description {
            lines.push(format!("  /** {} */", d));
        }
        lines.push(format!("  {}{}: {};", to_camel(&field.fd_name), optional, ts_type));
    }

    lines.push("}".to_string());
    lines.join("\n")
}

#[allow(dead_code)]
fn generate_discriminated_union(
    name: &str,
    discriminator: &str,
    variants: &[VariantDef],
    desc: &Option<String>,
) -> String {
    let mut lines = Vec::new();

    if let Some(d) = desc {
        lines.push(format!("/** {} */", d));
    }

    // Generate union type
    let variant_names: Vec<String> = variants
        .iter()
        .map(|v| format!("{}_{}", to_pascal(name), to_pascal(&v.vd_name)))
        .collect();

    // Handle empty variants - use `never` type for enums with no variants
    let union_type = if variant_names.is_empty() {
        "never".to_string()
    } else {
        variant_names.join(" | ")
    };

    lines.push(format!(
        "export type {} = {};",
        to_pascal(name),
        union_type
    ));
    lines.push("".to_string());

    // Generate individual variant interfaces
    for variant in variants {
        let variant_type_name = format!("{}_{}", to_pascal(name), to_pascal(&variant.vd_name));

        if let Some(d) = &variant.vd_description {
            lines.push(format!("/** {} */", d));
        }
        lines.push(format!("export interface {} {{", variant_type_name));
        lines.push(format!("  {}: '{}';", discriminator, variant.vd_name));

        for field in &variant.vd_fields {
            let optional = if field.fd_required { "" } else { "?" };
            let ts_type = field.fd_type.to_ts();
            if let Some(d) = &field.fd_description {
                lines.push(format!("  /** {} */", d));
            }
            lines.push(format!("  {}{}: {};", to_camel(&field.fd_name), optional, ts_type));
        }

        lines.push("}".to_string());
        lines.push("".to_string());
    }

    lines.join("\n")
}

#[allow(dead_code)]
fn generate_alias(name: &str, target: &crate::ir::TypeRef, desc: &Option<String>) -> String {
    let mut lines = Vec::new();
    if let Some(d) = desc {
        lines.push(format!("/** {} */", d));
    }
    lines.push(format!("export type {} = {};", to_pascal(name), target.to_ts()));
    lines.join("\n")
}

fn generate_primitive_alias(
    name: &str,
    prim_type: &str,
    format: Option<&str>,
    desc: &Option<String>,
) -> String {
    let mut lines = Vec::new();
    if let Some(d) = desc {
        lines.push(format!("/** {} */", d));
    }
    let ts_type = match (prim_type, format) {
        ("string", Some("uuid")) => "string",
        ("string", _) => "string",
        ("integer", _) | ("number", _) => "number",
        ("boolean", _) => "boolean",
        _ => "unknown",
    };
    lines.push(format!("export type {} = {};", to_pascal(name), ts_type));
    lines.join("\n")
}

fn generate_string_enum(name: &str, values: &[String], desc: &Option<String>) -> String {
    let mut lines = Vec::new();
    if let Some(d) = desc {
        lines.push(format!("/** {} */", d));
    }
    // Generate TypeScript string literal union: type Foo = "a" | "b" | "c";
    let union_values: Vec<String> = values.iter().map(|v| format!("\"{}\"", v)).collect();
    let union_type = if union_values.is_empty() {
        "never".to_string()
    } else {
        union_values.join(" | ")
    };
    lines.push(format!("export type {} = {};", to_pascal(name), union_type));
    lines.join("\n")
}

/// Convert to PascalCase
fn to_pascal(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize = true;
    for c in s.chars() {
        if c == '_' || c == '-' || c == '.' {  // Treat dots as word boundaries
            capitalize = true;
        } else if capitalize {
            result.push(c.to_ascii_uppercase());
            capitalize = false;
        } else {
            result.push(c);
        }
    }
    result
}

/// Convert to camelCase
fn to_camel(s: &str) -> String {
    let pascal = to_pascal(s);
    if pascal.is_empty() {
        return pascal;
    }
    let mut chars = pascal.chars();
    match chars.next() {
        Some(first) => first.to_ascii_lowercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}
